### ISSUE TITLE
Can I translate this repo into Chinese?

### ISSUE THREAD

**Issue by youngjuning** [sudheerj/reactjs-interview-questions#102]
I am the blogger of [juejin](https://juejin.cn/)（A community that helps developers grow）.

I want a translation authorization.

**Comment by youngjuning** [comment]
@sudheerj Hi. Any problem here?

**Comment by sudheerj** [comment]
@youngjuning  Sure. But make sure to mention about the original repo link in chinense translation repo.

**Comment by youngjuning** [comment]
@sudheerj  It should be noted that I am publishing a paid edition booklet after enriching and optimizing on the basis of this repo. 

The book will publish on [juein books](https://juejin.cn/books).

**Comment by youngjuning** [comment]
And the `youngjuning@aliyun.com` is my personal email.
