### ISSUE TITLE
How to Download the PDF and Epub version of this repository from the latest run on the actions tab.

### ISSUE THREAD

**Issue by MkVerma643** [sudheerj/reactjs-interview-questions#122]
Please Guide..

**Comment by shahul01** [comment]
download the artifacts
![image](https://user-images.githubusercontent.com/53307156/121933547-dab9d400-cd63-11eb-96e9-e7eeb04feab1.png)

**Comment by shahul01** [comment]
Download the artifacts


![image](https://user-images.githubusercontent.com/53307156/121933923-48fe9680-cd64-11eb-95be-547e42a2e275.png)

**Comment by ShubhamGore12** [comment]
thanks.

**Comment by SupriyaKHemanth** [comment]
the link is disabled

**Comment by narwanimonish** [comment]
Login to Github, then output will be downloadable.

**Comment by islomnumanovuz** [comment]
> Download the artifacts
> 
> ![image](https://user-images.githubusercontent.com/53307156/121933923-48fe9680-cd64-11eb-95be-547e42a2e275.png)

This was useful thanks

**Comment by shahul01** [comment]
if the artifacts are expired, you can manually create pdf from markdown, 
you can downlod readme.md from this repo 
go to any [conversion site](https://cloudconvert.com/md-to-pdf) to convert md to pdf file
