### ISSUE TITLE
Epub version questions rendering error

### ISSUE THREAD

**Issue by devevignesh** [sudheerj/reactjs-interview-questions#124]
I have downloaded the latest epub version and I got an error that says "error on line 1511 at column 6: Opening and ending tag mismatch: li line 0 and h1". 

I'm assuming that the template literals are not working with the epub version. 

<img width="734" alt="Screenshot 2021-06-18 at 11 02 43 PM" src="https://user-images.githubusercontent.com/31436276/122597646-4c0dc580-d089-11eb-8051-4419e534e3dc.png">

OS: macOS BigSur
Books: V3.2

**Comment by sudheerj** [comment]
Are there any issues with PDF version?

**Comment by devevignesh** [comment]
@sudheerj  No there are no issues with the PDF version. Thanks

**Comment by admapop** [comment]
Not sure if related but the ePub version when opened on iOS books app, it only has 21 pages

**Comment by bingalls** [comment]
`epubcheck` tells you that you are missing a closing </li> tag. I can send you a working epub file, but I'm not sure how to do so.
Should I create a pull request, with a /dist/ directory?

**Comment by sudheerj** [comment]
@bingalls No, it should be fixed README. Are you still replicating the issue?

**Comment by sudheerj** [comment]
Epub is no longer supported
