### ISSUE TITLE
Question 33: React 16.4+ had some changes wrt getDerivedStateFromProps

### ISSUE THREAD

**Issue by Harshit369** [sudheerj/reactjs-interview-questions#129]
`getDerivedStateFromProps` static method is now called on every re-render including any changes in the internal state.

![image](https://user-images.githubusercontent.com/7912702/126118826-89ae48bf-4e44-4483-88f8-7166c2d4d7b6.png)

[React Issue Ref](https://github.com/facebook/react/issues/12898)

@sudheerj

**Comment by sudheerj** [comment]
Thanks @Harshit369. I updated the image.
