### ISSUE TITLE
Epub has errors and its not fully opening in macbook/iphone

### ISSUE THREAD

**Issue by mhaneef50673** [sudheerj/reactjs-interview-questions#150]

**Comment by santirequelme** [comment]
how's to download the ePub file? thanks!

**Comment by Kasmanaft** [comment]
![61825C6D-83AC-436B-897E-D0CA74813327](https://user-images.githubusercontent.com/148225/170818628-2382f3a7-9de0-4150-b4e8-a767965517a8.jpeg)

@sudheerj
