### ISSUE TITLE
Question 31 and 78 are duplicated

### ISSUE THREAD

**Issue by MujunZ** [sudheerj/reactjs-interview-questions#16]
31. What is the difference between createElement and cloneElement?

JSX elements will be transpiled to React.createElement() functions to create React elements which are going to be used for the object representation of UI. Whereas cloneElement is used to clone an element and pass it new props.

78. What is the difference between createElement() and cloneElement() methods?
In JSX the React element is transpiled to React.createElement() which represents an UI element. Whereas React.cloneElement() is used in order to clone an element and pass it new props.

**Comment by sudheerj** [comment]
Thank you @MujunZ for the finding. I will fix it with a new question.

**Comment by sudheerj** [comment]
Fixed
