### ISSUE TITLE
React Forget

### ISSUE THREAD

**Issue by danieldanielecki** [sudheerj/reactjs-interview-questions#179]
There might be a significant change coming about the `React.memo` called `React Forget`.
If they'd release it, I'd advise adding a question regarding that topic.
Source: https://www.youtube.com/watch?v=lGEMwh32soc

**Comment by sudheerj** [comment]
Okay. Thanks for the suggestion

**Comment by sudheerj** [comment]
The question related to this feature will be once available in ReactJS. We will close this issue for now.
