### ISSUE TITLE
Question 15 Enhancement. 

### ISSUE THREAD

**Issue by umair-khanzada** [sudheerj/reactjs-interview-questions#18]
How to pass a parameter to an event handler or callback?

There is another way I think you need to add this as well, It is quite simple and easy to understand.
```
methodName = (parameter) => () => {
  //Do something with parameter.
  console.log("parameter", parameter)
};

<button onClick={this.methodName('value you want to pass')} >Click</button>
```

**Comment by sudheerj** [comment]
Thanks @umair-khanzada. I updated the question with this approach.
