### ISSUE TITLE
How to download PDF File for this questions

### ISSUE THREAD

**Issue by rahuldayal** [sudheerj/reactjs-interview-questions#195]
How to download PDF File for this questions

**Comment by rishi-raj-jain** [comment]
- Open any Action in https://github.com/sudheerj/reactjs-interview-questions/actions
- Scroll to the bottom
- Click "Output" under Artifacts
- Voila!

**Comment by random-play** [comment]
> * Open any Action in https://github.com/sudheerj/reactjs-interview-questions/actions
> * Scroll to the bottom
> * Click "Output" under Artifacts
> * Voila!

need account login, otherwise cannot download!

**Comment by rishi-raj-jain** [comment]
@random-play I think just a github account would do

**Comment by random-play** [comment]
> @random-play I think just a github account would do

yeah, just a github account

**Comment by naveenrawat51** [comment]
Why don't you use ctrl + p and save it in pdf format :-)
