### ISSUE TITLE
Outdated questions

### ISSUE THREAD

**Issue by frejp** [sudheerj/reactjs-interview-questions#219]
Many of the questions and answers are outdated.
Example: No one will ask questions the relates to class components, setState etc. 
This is just a waste of time, plus you make people dumber.

**Comment by sudheerj** [comment]
The repo has been created few years ago and there is a plan to update with functional components and also classes solution will be added, hidden by default. Do you think that every organization  rewrite classes with functional components? If you don’t have patience and don’t know how to communicate then either just contribute with PRs or be calm without wasting others time.
