### ISSUE TITLE
Comments to improve the content

### ISSUE THREAD

**Issue by omerg** [sudheerj/reactjs-interview-questions#22]
Hello @sudheerj , thank you for this wonderful collection of questions! Here are some of my comments to improve the document:

- **Duplicity: 82 and 109**
82 and 109 are almost the same and can be considered as duplicate ( 82: "Why we need to pass a function to setState()?" - 109: "Why function is preferred over object for setState?" )
- **Duplicity: 87 and 118**
87 and 118 refer to a very similar topic and can be merged ( 87: "Why should component names start with capital letter?" - 118: "Why React component names must begin with a capital letter?" )
- **102: "How to listen to state changes?"** 
componentWillUpdate is deprecated. 
- **182: "What are Redux selectors and why to use them?"**
 I think why to use them is not mentioned. One specific need is when using them with "select" method of saga's.
- **205: How to use TypeScript in create-react-app application?**
create-react-app now supports TypeScript natively: see: https://github.com/wmonk/create-react-app-typescript
- **208: What is an action in Redux?**
Should go under _redux_ section instead of _misc_.
- **209: Does the statics object work with ES6 classes in React?**
There is a third way of writing statics; that is, outside the class:
```
class Component extends React.Component {
   ....
}

Component.propTypes = {...}
Component.someMethod = function(){....}
```
- **215: Why are inline ref callbacks or functions not recommended?**
There is no need to use both since React.createRef brought with v16.3 is much neater than both: https://reactjs.org/blog/2018/03/29/react-v-16-3.html#createref-api 
- **226: "What are hooks?"**
> Hooks are a new feature proposal that lets you...

Hooks are no more a proposal

**Comment by sudheerj** [comment]
I will go through all of them. Thanks.

**Comment by sudheerj** [comment]
@omerg I covered all the above cases. Thanks for points. Anyway I will make more improvements in coming days.
