### ISSUE TITLE
Redux

### ISSUE THREAD

**Issue by Vandhana-Mohan** [sudheerj/reactjs-interview-questions#228]
Could you go over redux and content-api and why they are more popular than useState

**Comment by sudheerj** [comment]
@Vandhana-Mohan Thanks for the suggestion. Can you contribute with PR?

**Comment by Vandhana-Mohan** [comment]
No, I requested if you could teach us redux and content-api and why they are more popular than useState.

**Comment by sudheerj** [comment]
Noted. Thanks. We will have questions on this in future
