### ISSUE TITLE
I want to convert the Class components examples into Functions Components

### ISSUE THREAD

**Issue by Shahidullah-Muffakir** [sudheerj/reactjs-interview-questions#235]
Hi guys,
It is one of the great resource for interview preparation, thanks for this.
but I have one suggestion, can I convert the examples written in Class component into Function Component?
I will be glad to do it.
Regards

**Comment by sudheerj** [comment]
Thank you. Can you please create a PR for each question separately?

**Comment by Shahidullah-Muffakir** [comment]
Yes, I will do. Thank you.
