### ISSUE TITLE
Question 2 to 10 are not in correct order.

### ISSUE THREAD

**Issue by chetannada** [sudheerj/reactjs-interview-questions#241]
In Readme file, The sequence of Quetion 2 to 10 are not in correct order.

for ex. Question no. 2: What are the major features of React?
and in answer it shows Answer no. 3.
It will be the same upto Question 10.

There are Two answers under 10 number.

**Comment by sudheerj** [comment]
@chetannada  Thanks for creating the PR. Please check my comment in PR
