### ISSUE TITLE
Duplication of questions

### ISSUE THREAD

**Issue by WestCoast5550** [sudheerj/reactjs-interview-questions#26]
It seems like 44, 87, 118 are duplicating.
I think I have already saw questions that are also duplicating.
Probably it is better to separate categories to subcategories to avoid that?

**Comment by sudheerj** [comment]
Thank you for notifying this. I will check them very soon.

**Comment by sudheerj** [comment]
Fixed. I will review other questions for  eliminating any duplicates.
