### ISSUE TITLE
Incorrect code sample for Q 335

### ISSUE THREAD

**Issue by devrutul** [sudheerj/reactjs-interview-questions#270]
For functional component, `setCountry` is used, it should be `setMessage`

`function App() {
  const [message, setMessage] = useState("This is a functional component");
  const updateMessage = () => {
    setCountry("Updating the functional component");
  };
  return (
    <div className="App">
      <h1>{message} </h1>
      <button onClick={updateMessage}>Click me!!</button>
    </div>
  );
}`

by the way nice work👍

**Comment by sudheerj** [comment]
Fixed. Thank for your words.
