### ISSUE TITLE
Table of Contents is too long maybe make it a collapsible section 

### ISSUE THREAD

**Issue by sahilbakoru** [sudheerj/reactjs-interview-questions#273]
## Table of Contents is too long maybe make it a collapsible section  .
Just like shown below.

https://github.com/sudheerj/reactjs-interview-questions/assets/68190549/ecb2f42a-aee7-4c4d-b058-8d655ef7a351

**Comment by sudheerj** [comment]
The table of contents is helpful to see all the questions at the same time. If we close it by default, reader may not get idea to expand them.

**Comment by sahilbakoru** [comment]
Can we open it by default ? readers can choose to close if they want.

**Comment by sanketmali09** [comment]
In Markdown, you can create collapsible sections like the one you've shown
using HTML <details> and <summary> elements, just as you've demonstrated in
your example. Here's how to do it:

   1.

   Use <details> and <summary>: These HTML elements are used to define the
   collapsible section. The <summary> element is the clickable header that
   users will click on to expand or collapse the content.
   2.

   Place your content inside the <details> element: You can include any
   Markdown content, such as headings, lists, code blocks, or paragraphs,
   within the <details> element. This content will be hidden by default
   when the section is collapsed.
   3.

   Keep the <summary> element concise: The <summary> element should provide
   a brief and meaningful label for the collapsible section. Users will click
   on this label to toggle the visibility of the content.
   4.

   Use indentation: While it's not required, indenting the content within
   the <details> element helps improve readability and maintainability,
   especially for larger sections of content.
   5.

   Use backticks for code blocks: If you want to include code blocks, as
   you did in your example, use triple backticks (```) to define the code
   block and specify the language (e.g., js for JavaScript).

Remember that the support for HTML in Markdown may vary depending on the
platform or renderer you're using. Most Markdown renderers should support
<details> and <summary>, but it's a good idea to test your Markdown
documents in the specific environment where you intend to use them to
ensure proper rendering and interactivity.

**Comment by sahilbakoru** [comment]
chat GPT is that you ?

**Comment by sanketmali09** [comment]
Ok i will send you tomorrow

**Comment by sahilbakoru** [comment]
## I have made a pull request  for that, video and code is also there.
 ### check the pull request : https://github.com/sudheerj/reactjs-interview-questions/pull/274

**Comment by sudheerj** [comment]
@sahilbakoru Thanks added
