### ISSUE TITLE
Make a website for this github repo 

### ISSUE THREAD

**Issue by creator79** [sudheerj/reactjs-interview-questions#284]
Building a React website for a GitHub repository can provide a user-friendly interface for browsing questions and answers. If you have any specific questions or if there's anything you'd like assistance with as you work on your project, feel free to let me know! Whether it's about React components, GitHub API integration, or any other related topic, I'm here to help.

Deployed Link :- https://react-interview-prep.vercel.app/

**Comment by creator79** [comment]
@sudheerj please look into that

**Comment by sudheerj** [comment]
@creator79 Thanks for the feedback. I’m going to update the repo and create a new site. I will look for your help if needed.
