### ISSUE TITLE
Question 11 note

### ISSUE THREAD

**Issue by engmagdy87** [sudheerj/reactjs-interview-questions#3]
Hi @sudheerj 
in Q11, u wrote 
```
Note: The only place you can directly assign to the state object is in constructor.
```
but u can remove the constructor from the component and access the state object
```
class Hello extends Component {
       state= {
           a:"hello",
           b:" react"
       }
render(){
    const {a,b} = this.state;
    return(
        <div>{a + b}</div>
    )
   }
 }
```

**Comment by sudheerj** [comment]
Thanks for pointing out. I corrected accordingly. But the class field declaration syntax is specific to latest javascript and available only for few browsers.
