### ISSUE TITLE
About "When to use Class Component over Function Component"

### ISSUE THREAD

**Issue by thongncvn** [sudheerj/reactjs-interview-questions#51]
https://github.com/sudheerj/reactjs-interview-questions#when-to-use-a-class-component-over-a-function-component

As of today, I believe that we can use Function Component for almost every use case, except when implementing Error Boundaries. Could you please share your opinion about this?

**Comment by sudheerj** [comment]
Yes, you are right. That is the reason I mentioned the second sentence.
