### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by ianwalter** [sudheerj/reactjs-interview-questions#54]
This is a great list. Not only for interviews but also for just getting up to speed with React, so thank you. If I can piggyback on #22, here are some suggestions I thought about while browsing the list:

* **105:** This isn't React-specific and I think removing it would help make the content more focused.
* **107:** Maybe mention why this is necessary instead of just using `autofocus`?

**Comment by sudheerj** [comment]
Hello Ian,

              Thanks for the suggestion. I will review and update it.
