### ISSUE TITLE
199 and 200 are extremely opinionated and not fact based

### ISSUE THREAD

**Issue by kitsunekyo** [sudheerj/reactjs-interview-questions#55]
as stated in the title, the comparison of react to angular and vuejs is fairly opinionated and serves no real benefit for interviews. at most, these notes will confuse interviewees.

devs should base the answer to these two questions on their experience, not heresy or find themselves in trouble explaining further.

I'd recommend removing these two questions.

**Comment by sudheerj** [comment]
IMHO, these answers helpful to give the base parameters for comparing the frameworks or technologies. I agree that opinion might change based on their experience. So I mention about this answer with a note.
