### ISSUE TITLE
please help me on this

### ISSUE THREAD

**Issue by anima-bishi** [sudheerj/reactjs-interview-questions#68]
'm using node and I tried to create a simple react-app by using the following commands:

npm install -g create-react-app
create-react-app project-name
npm start

I had no issues in creating an app and my app got created successfully.

Inside that directory, you can run several commands:

npm start
Starts the development server.

npm run build
Bundles the app into static files for production.

npm test
Starts the test runner.

npm run eject
Removes this tool and copies build dependencies, configuration files
and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

cd appname
npm start

Happy hacking!_**

But when I tried to run my start script I'm facing an error

events.js:292
throw er; // Unhandled 'error' event
^

Error: spawn cmd ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
at onErrorNT (internal/child_process.js:469:16)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
at onErrorNT (internal/child_process.js:469:16)
at processTicksAndRejections (internal/process/task_queues.js:84:21) {
errno: 'ENOENT',
code: 'ENOENT',
syscall: 'spawn cmd',
path: 'cmd',
spawnargs: [ '/s', '/c', 'start', '""', '/b', '"http://localhost:3000/"' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reactawesome@0.1.0 start: react-scripts start
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactawesome@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\ADMIN\AppData\Roaming\npm-cache_logs\2020-07-01T09_26_11_748Z-debug.log

E:\myreactapp\reactawesome>

please help me on this error..how to solve.
react

**Comment by maaaaciej** [comment]
Did your remember to CD into the new project before trying to run the start script? I've done that many times before.
