### ISSUE TITLE
Fix the answer of 303. How to fetch data with React Hooks?

### ISSUE THREAD

**Issue by bcjohnblue** [sudheerj/reactjs-interview-questions#98]
Return `promise` in `useEffect` is forbidden. The right way should be

```javascript
useEffect(() => {
  (async () => {
    const result = await axios(
      'http://hn.algolia.com/api/v1/search?query=react',
    );

    setData(result.data);
  })()
}, []);
```

**Comment by itstanmaykhandelwal** [comment]
useEffect(async () => {
    const result = await axios(
      "https://hn.algolia.com/api/v1/search?query=redux",
    );
 
    setData(result.data);
  });

I think this is the Write way

**Comment by swprqa** [comment]
@bcjohnblue is correct. @itstanmaykhandelwal option returns promise implicitly, and function passed to useEffect should return undefined or a cleanup function.

**Comment by chankruze** [comment]
> Return `promise` in `useEffect` is forbidden. The right way should be
> 
> ```js
> useEffect(() => {
>   (async () => {
>     const result = await axios(
>       'http://hn.algolia.com/api/v1/search?query=react',
>     );
> 
>     setData(result.data);
>   })()
> }, []);
> ```

This is correct
